apiVersion: v1
kind: Service
metadata:
  labels:
    name: zk-operator
  name: zk-operator
spec:
  type: ClusterIP
  selector:
    app: zk-operator
  ports:
  - name: web
    port: 80
    targetPort: 8472
  - name: healthz
    port: 8081
    targetPort: 8081
    