apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups: ["operator.zerok.ai"]
  resources: ["zerokops"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
- apiGroups: ["operator.zerok.ai"]
  resources: ["zerokops/finalizers"]
  verbs: ["update"]
- apiGroups: ["operator.zerok.ai"]
  resources: ["zerokops/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["v1",""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "update"]
- apiGroups: ["v1",""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get"]