apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-operator-role
rules:
- apiGroups: ["operator.zerok.ai"]
  resources: ["zerokinstrumentations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
- apiGroups: ["operator.zerok.ai"]
  resources: ["zerokops/finalizers"]
  verbs: ["update"]
- apiGroups: ["operator.zerok.ai"]
  resources: ["zerokops/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["v1",""]
  resources: ["namespaces"]
  verbs: ["list","delete", "watch","get"]
- apiGroups: ["v1",""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["v1",""]
  resources: ["pods"]
  verbs: ["list"]