---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.zerok.ai.zerok.ai
  resources:
  - zerokcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.zerok.ai.zerok.ai
  resources:
  - zerokcrds/finalizers
  verbs:
  - update
- apiGroups:
  - operator.zerok.ai.zerok.ai
  resources:
  - zerokcrds/status
  verbs:
  - get
  - patch
  - update
