apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: zerok-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Zerokop is the Schema for the zerokops API
      displayName: Zerokop
      kind: Zerokop
      name: zerokops.operator.zerok.ai
      statusDescriptors:
      - description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
          Important: Run "make" to regenerate code after modifying this file'
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: For managing zerok resources
  displayName: zkoperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apm
  - debugging
  links:
  - name: Zerok Operator
    url: https://zerok-operator.domain
  maturity: alpha
  provider:
    name: zerok
    url: zerok.ai
  version: 0.0.1
