# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zerokops.operator.zerok.ai
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: zk-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
