apiVersion: v1
data:
  operator-config.yaml: |+
    redis:
      host: redis.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      dbs:
        scenario_db: 6
        integration_db: 9
        executor_attr_db: 4
    http:
      port: 8472
      exceptionPath: /exception
    obfuscationRulesSync:
      path: /v1/o/org/obfuscation/rule/list
      pollingInterval: 300
      db: 10
    clusterContext:
      path: /i/clusterContext
      cloudAddr: px.testacloud01.getanton.com
      port: 443
    zkcloud:
      host: api.testacloud01.getanton.com
      port: 443
    scenarioSync:
      path: /v1/o/cluster/<clusterid>/scenario
      pollingInterval: 30
      db: 6
    integrationSync:
      path: /v1/o/cluster/<clusterid>/integration
      pollingInterval: 30
      db: 9
    configurationSync:
      path: /v1/o/cluster/<clusterid>/configuration
      pollingInterval: 30
      apiPath: /i/configuration
    executorAttributesSync:
      path: /v1/o/cluster/<clusterid>/executorAttributes
      pollingInterval: 300
      db: 4
    operatorLogin:
      path: /v1/o/auth/login
      clusterSecretName: cluster-info
      clusterKeyData: clusterKey
      apiKeyData: apiKey
      clusterKeyNamespace: zk-client
      maxRetries: 3
    wspClient:
      host: zk-wsp-client.zk-client.svc.cluster.local
      port: 8987
      path: /request
      destinationHeader: X-PROXY-DESTINATION
    clusterHealthSync:
      path: /v1/o/clustermeta/update
      syncInterval: 10
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-operator