apiVersion: v1
data:
  operator-config.yaml: |+
    redis:
      host: redis.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      dbs:
        image_db: 7
        scenario_db: 6
        integration_db: 9
    webhook:
      namespace: zk-client
      service: zk-operator-inject
      name: zk-webhook
      path: /zk-injector
      port: 8473
    http:
      port: 8472
      exceptionPath: /exception
    clusterContext:
      path: /i/clusterContext
      cloudAddr: px.devcloud01.getanton.com
      port: 443
    zkcloud:
      host: api.devcloud01.getanton.com
      port: 443
    scenarioSync:
      path: /v1/o/cluster/<clusterid>/scenario
      pollingInterval: 30
      db: 6
    integrationSync:
      path: /v1/o/cluster/<clusterid>/integration
      pollingInterval: 30
      db: 9
    configurationSync:
      path: /v1/o/cluster/<clusterid>/configuration
      pollingInterval: 30
      apiPath: /i/configuration
    operatorLogin:
      path: /v1/o/auth/login
      clusterSecretName: cluster-info
      clusterKeyData: clusterKey
      apiKeyData: apiKey
      clusterKeyNamespace: zk-client
      maxRetries: 3
    wspClient:
      host: zk-wsp-client.zk-client.svc.cluster.local
      port: 8987
      path: /request
      destinationHeader: X-PROXY-DESTINATION
    initContainer:
      pollingInterval: 30
    instrumentation:
      otelArgument: -javaagent:/opt/zerok/opentelemetry-javaagent-1.27.0.jar -Dotel.javaagent.extensions=/opt/zerok/zk-otel-extension-1.0.jar -Dotel.traces.exporter=zerok
      pollingInterval: 30 #seconds
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-operator