apiVersion: v1
data:
  operator-config.yaml: |+
    redis:
      host: redis.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      dbs:
        scenario_db: 6
        integration_db: 9
        executor_attr_db: 4
    http:
      port: 8472
      exceptionPath: /exception
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-operator