---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zk-operator
  namespace: zk-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zk-operator-leader-election-role
  namespace: zk-client
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-operator-role
rules:
- apiGroups:
  - operator.zerok.ai
  resources:
  - zerokinstrumentations
  verbs:
  - create
  - get
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - patch
    - list
    - watch
    - get
- apiGroups:
  - operator.zerok.ai
  resources:
  - zerokops/finalizers
  verbs:
  - update
- apiGroups:
  - operator.zerok.ai
  resources:
  - zerokops/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - delete
  - watch
  - get
- apiGroups:
  - v1
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - v1
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zk-operator-leader-election-rolebinding
  namespace: zk-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zk-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: zk-operator
  namespace: zk-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zk-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zk-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: zk-operator
  namespace: zk-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zk-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zk-operator-role
subjects:
- kind: ServiceAccount
  name: zk-operator
  namespace: zk-client