// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.8
// source: envoy/extensions/access_loggers/file/v3/FileAccessLog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileAccessLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *FileAccessLog) Reset() {
	*x = FileAccessLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileAccessLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAccessLog) ProtoMessage() {}

func (x *FileAccessLog) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAccessLog.ProtoReflect.Descriptor instead.
func (*FileAccessLog) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescGZIP(), []int{0}
}

func (x *FileAccessLog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileAccessLog) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto protoreflect.FileDescriptor

var file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x65,
	0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x73, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x76, 0x33, 0x22, 0x3b, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescOnce sync.Once
	file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescData = file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDesc
)

func file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescGZIP() []byte {
	file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescData = protoimpl.X.CompressGZIP(file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescData)
	})
	return file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDescData
}

var file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_goTypes = []interface{}{
	(*FileAccessLog)(nil), // 0: envoy.extensions.access_loggers.file.v3.FileAccessLog
}
var file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_init() }
func file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_init() {
	if File_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileAccessLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_msgTypes,
	}.Build()
	File_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto = out.File
	file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_rawDesc = nil
	file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_goTypes = nil
	file_envoy_extensions_access_loggers_file_v3_FileAccessLog_proto_depIdxs = nil
}
