apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: replay-service-monitor
  name: replay-service-monitor
  namespace: default
spec:
  endpoints:
  - interval: 60s
    port: web
  - interval: 60s
    port: reloader-web
  selector:
    matchLabels:
      name: replay-service