redis:
  host: localhost
  port: 6379
  readTimeout: 20
  pollingInterval: 30 #seconds
  db: 7

webhook:
  namespace: zerok-injector
  service: zerok-injector
  name: zerok-webhook
  path: /zk-injector
  port: 8443

zkcloud:
  restartPath: /restart
  port: 8442

logs:
  color: true
  level: DEBUG

local: true