redis:
  host: redis.redis.svc.cluster.local
  port: 6379
  readTimeout: 20
  pollingInterval: 30 #seconds
  db: 7

webhook:
  namespace: zk-operator-system
  service: zk-operator-inject
  name: zk-webhook
  path: /zk-injector
  port: 8473

zkcloud:
  restartPath: /restart
  port: 8472

logs:
  color: true
  level: DEBUG

local: false
